import {
  Auction,
  Lot,
  AuctionItem,
  AdditionalExpense,
  MaintenanceRecord,
  Advertisement,
  SaleRecord,
  Contact,
  AppDocument,
  ActivityLog,
  AlertItem,
} from "./types";

export const initialAuctions: Auction[] = [
  {
    id: "auc-1",
    name: "Leilão Judicial TRT-2 - Ativos de TI e Máquinas",
    auctioneer: "Sodré Santoro Leilões",
    platform: "Sodré Santoro Online",
    processNumber: "0001234-88.2024.5.02.0002",
    responsibleEntity: "TRT da 2ª Região - São Paulo",
    auctionType: "Judicial",
    auctionDate: "2026-06-15",
    city: "São Paulo",
    state: "SP",
    pickupAddress: "Av. do Estado, 4500 - Mooca, São Paulo - SP",
    commissionPercentage: 5,
    notes: "Leilão de bens arrecadados em falência industrial. Excelentes equipamentos de tecnologia.",
    editalUrl: "https://exemplo.com.br/edital-trt2.pdf",
    status: "concluido",
    documentsCount: 4,
  },
  {
    id: "auc-2",
    name: "Leilão de Frota Corporativa Petrobras 2026.1",
    auctioneer: "Superbid Exchange",
    platform: "Superbid Marketplace",
    processNumber: "PETRO-2026-FROTA-003",
    responsibleEntity: "Petróleo Brasileiro S.A.",
    auctionType: "Corporativo",
    auctionDate: "2026-07-02",
    city: "Campinas",
    state: "SP",
    pickupAddress: "Rodovia Anhanguera, Km 104 - Galpão 03, Campinas - SP",
    commissionPercentage: 5,
    notes: "Veículos leves e utilitários da frota de operações com revisões periódicas em dia.",
    editalUrl: "https://exemplo.com.br/edital-petrobras.pdf",
    status: "concluido",
    documentsCount: 3,
  },
  {
    id: "auc-3",
    name: "Leilão Caixa Econômica Federal - Bens Móveis Recuperados",
    auctioneer: "Frazão Leilões",
    platform: "Frazão Leiloeiros Online",
    processNumber: "CEF-SP-2026-092",
    responsibleEntity: "Caixa Econômica Federal",
    auctionType: "Extrajudicial",
    auctionDate: "2026-07-20",
    city: "Guarulhos",
    state: "SP",
    pickupAddress: "Rua do Leilão, 1200 - Bonsucesso, Guarulhos - SP",
    commissionPercentage: 5,
    notes: "Mobiliário corporativo completo, servidores e aparelhos de ar condicionado.",
    editalUrl: "https://exemplo.com.br/edital-cef.pdf",
    status: "concluido",
    documentsCount: 2,
  },
  {
    id: "auc-4",
    name: "Leilão de Sucata e Maquinário Industrial - Falência Metalúrgica",
    auctioneer: "Megaleilões",
    platform: "Megaleilões",
    processNumber: "1004562-11.2023.8.26.0100",
    responsibleEntity: "2ª Vara de Falências e Recuperações SP",
    auctionType: "Judicial",
    auctionDate: "2026-08-10",
    city: "Sorocaba",
    state: "SP",
    pickupAddress: "Distrito Industrial, Rua 8, Nº 330, Sorocaba - SP",
    commissionPercentage: 5,
    notes: "Tornos CNC, prensas hidráulicas, pontes rolantes e estamparia.",
    editalUrl: "https://exemplo.com.br/edital-metalurgica.pdf",
    status: "participando",
    documentsCount: 1,
  },
];

export const initialLots: Lot[] = [
  {
    id: "lot-101",
    auctionId: "auc-1",
    lotNumber: "Lote 15",
    description: "Lote contendo 5 Notebooks Dell Latitude 5420 Core i7 e 2 Monitores Dell 27 Ultrawide",
    winningBid: 12500.0,
    auctioneerCommission: 625.0, // 5%
    adminFee: 250.0,
    taxes: 120.0,
    transportCost: 350.0,
    disassemblyCost: 0,
    loadingCost: 100.0,
    storageCost: 0,
    otherCosts: 50.0,
    totalLotCost: 13995.0,
    itemCount: 7,
    paymentDeadline: "2026-06-18",
    pickupDeadline: "2026-06-25",
    paymentStatus: "pago",
    pickupStatus: "retirado",
    notes: "Equipamentos em bom estado estético oriundos de escritório executivo.",
  },
  {
    id: "lot-102",
    auctionId: "auc-2",
    lotNumber: "Lote 04",
    description: "Utilitário Pick-up Toyota Hilux CD 4x4 Diesel 2021/2021",
    winningBid: 115000.0,
    auctioneerCommission: 5750.0,
    adminFee: 1200.0,
    taxes: 2800.0,
    transportCost: 1500.0, // Guincho plataforma
    disassemblyCost: 0,
    loadingCost: 0,
    storageCost: 300.0,
    otherCosts: 250.0,
    totalLotCost: 126800.0,
    itemCount: 1,
    paymentDeadline: "2026-07-05",
    pickupDeadline: "2026-07-12",
    paymentStatus: "pago",
    pickupStatus: "retirado",
    notes: "Veículo rodando perfeitamente. Pequeno amassado no para-choque traseiro.",
  },
  {
    id: "lot-103",
    auctionId: "auc-3",
    lotNumber: "Lote 42",
    description: "Lote de Ar Condicionado Split Industrial Inverter Carrier 60.000 BTUs (3 Unidades)",
    winningBid: 7800.0,
    auctioneerCommission: 390.0,
    adminFee: 180.0,
    taxes: 80.0,
    transportCost: 400.0,
    disassemblyCost: 300.0,
    loadingCost: 150.0,
    storageCost: 0,
    otherCosts: 0,
    totalLotCost: 9300.0,
    itemCount: 3,
    paymentDeadline: "2026-07-23",
    pickupDeadline: "2026-07-30",
    paymentStatus: "pago",
    pickupStatus: "retirado",
    notes: "Necessita de higienização prévia e carga de gás em 1 das unidades.",
  },
  {
    id: "lot-104",
    auctionId: "auc-1",
    lotNumber: "Lote 28",
    description: "Servidor Rack Dell PowerEdge R740xd com 64GB RAM e 4TB SAS Storage",
    winningBid: 8500.0,
    auctioneerCommission: 425.0,
    adminFee: 200.0,
    taxes: 90.0,
    transportCost: 180.0,
    disassemblyCost: 0,
    loadingCost: 50.0,
    storageCost: 0,
    otherCosts: 0,
    totalLotCost: 9445.0,
    itemCount: 1,
    paymentDeadline: "2026-06-18",
    pickupDeadline: "2026-06-25",
    paymentStatus: "pago",
    pickupStatus: "retirado",
    notes: "Servidor funcionando 100%, testado na bancada.",
  },
];

export const initialItems: AuctionItem[] = [
  {
    id: "itm-1",
    code: "LEIL-2026-001",
    lotId: "lot-101",
    auctionId: "auc-1",
    category: "Informática",
    subcategory: "Notebooks",
    name: "Notebook Dell Latitude 5420 i7 11ª Ger 16GB SSD 512GB",
    description: "Notebook corporativo Dell Latitude 5420, processador Core i7 1185G7, 16GB RAM DDR4, SSD NVMe 512GB, Tela 14 FHD IPS.",
    brand: "Dell",
    model: "Latitude 5420",
    serialNumber: "7K9L2M3",
    formerAssetTag: "PATR-TRT-08921",
    quantity: 1,
    condition: "seminovo",
    operationalState: "funcionando",
    location: {
      warehouse: "Galpão Principal",
      pavilion: "Setor A",
      aisle: "Corredor 2",
      shelfUnit: "Estante 03",
      shelfTier: "Prateleira B",
      customText: "Galpão Principal > Setor A > Corredor 2 > Estante 03 > Prateleira B",
    },
    photos: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
    ],
    primaryPhoto: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
    status: "vendido",
    originalCost: 1999.29,
    assignedPercent: 14.28,
    apportionedCost: 1999.29,
    additionalCosts: 150.0, // Formatação + Licença
    realTotalCost: 2149.29,
    estimatedMarketMin: 3200.0,
    estimatedMarketAvg: 3600.0,
    estimatedMarketMax: 4000.0,
    evaluationSource: "Mercado Livre / OLX Anúncios Ativos",
    evaluationDate: "2026-06-20",
    evaluationLinks: "https://mercadolivre.com.br/dell-5420",
    listedPrice: 3500.0,
    isAdvertised: true,
    isSold: true,
    dateAdded: "2026-06-16",
    daysInStock: 22,
    archived: false,
  },
  {
    id: "itm-2",
    code: "LEIL-2026-002",
    lotId: "lot-101",
    auctionId: "auc-1",
    category: "Informática",
    subcategory: "Notebooks",
    name: "Notebook Dell Latitude 5420 i7 11ª Ger 16GB SSD 512GB #2",
    description: "Notebook corporativo Dell Latitude 5420, processador Core i7 1185G7, 16GB RAM DDR4, SSD NVMe 512GB.",
    brand: "Dell",
    model: "Latitude 5420",
    serialNumber: "7K9L2M4",
    formerAssetTag: "PATR-TRT-08922",
    quantity: 1,
    condition: "seminovo",
    operationalState: "funcionando",
    location: {
      warehouse: "Galpão Principal",
      pavilion: "Setor A",
      aisle: "Corredor 2",
      shelfUnit: "Estante 03",
      shelfTier: "Prateleira B",
      customText: "Galpão Principal > Setor A > Corredor 2 > Estante 03 > Prateleira B",
    },
    photos: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
    ],
    primaryPhoto: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
    status: "anunciado",
    originalCost: 1999.29,
    assignedPercent: 14.28,
    apportionedCost: 1999.29,
    additionalCosts: 80.0, // Limpeza interna
    realTotalCost: 2079.29,
    estimatedMarketMin: 3200.0,
    estimatedMarketAvg: 3550.0,
    estimatedMarketMax: 3900.0,
    listedPrice: 3450.0,
    isAdvertised: true,
    isSold: false,
    dateAdded: "2026-06-16",
    daysInStock: 41,
    archived: false,
  },
  {
    id: "itm-3",
    code: "LEIL-2026-003",
    lotId: "lot-101",
    auctionId: "auc-1",
    category: "Informática",
    subcategory: "Monitores",
    name: "Monitor Dell Ultrawide 27 WQHD 144Hz S2721DGF",
    description: "Monitor Gamer e Profissional Dell 27 polegadas WQHD Quad HD 1ms IPS.",
    brand: "Dell",
    model: "S2721DGF",
    serialNumber: "CN-09821A",
    formerAssetTag: "PATR-TRT-09101",
    quantity: 1,
    condition: "seminovo",
    operationalState: "funcionando",
    location: {
      warehouse: "Galpão Principal",
      pavilion: "Setor B",
      aisle: "Corredor 1",
      shelfUnit: "Estante 01",
      shelfTier: "Prateleira A",
      customText: "Galpão Principal > Setor B > Corredor 1 > Estante 01",
    },
    photos: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80",
    ],
    primaryPhoto: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80",
    status: "disponivel",
    originalCost: 1999.29,
    assignedPercent: 14.28,
    apportionedCost: 1999.29,
    additionalCosts: 0,
    realTotalCost: 1999.29,
    estimatedMarketMin: 2100.0,
    estimatedMarketAvg: 2450.0,
    estimatedMarketMax: 2700.0,
    listedPrice: 2400.0,
    isAdvertised: false,
    isSold: false,
    dateAdded: "2026-06-16",
    daysInStock: 41,
    archived: false,
  },
  {
    id: "itm-4",
    code: "LEIL-2026-004",
    lotId: "lot-102",
    auctionId: "auc-2",
    category: "Veículos",
    subcategory: "Utilitários / Pick-ups",
    name: "Toyota Hilux CD SRV 4x4 2.8 Diesel Aut. 2021/2021",
    description: "Pick-up completa com tração 4x4, câmbio automático, 89.000 km rodados, capota marítima e protetor de caçamba.",
    brand: "Toyota",
    model: "Hilux SRV CD 4x4",
    serialNumber: "Chassi: 8AJBA3CD4M129812",
    formerAssetTag: "PETRO-FROTA-112",
    quantity: 1,
    condition: "usado",
    operationalState: "funcionando",
    location: {
      warehouse: "Pátio Externo",
      pavilion: "Vaga 14",
      customText: "Pátio Externo - Vaga Coberta 14",
    },
    photos: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    ],
    primaryPhoto: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
    status: "anunciado",
    originalCost: 126800.0,
    assignedPercent: 100,
    apportionedCost: 126800.0,
    additionalCosts: 3200.0, // Polimento, martelinho de ouro e troca de óleo
    realTotalCost: 130000.0,
    estimatedMarketMin: 165000.0,
    estimatedMarketAvg: 178000.0,
    estimatedMarketMax: 188000.0,
    evaluationSource: "Tabela FIPE R$ 181.400 + OLX SP",
    evaluationDate: "2026-07-10",
    listedPrice: 174900.0,
    isAdvertised: true,
    isSold: false,
    dateAdded: "2026-07-03",
    daysInStock: 24,
    archived: false,
  },
  {
    id: "itm-5",
    code: "LEIL-2026-005",
    lotId: "lot-103",
    auctionId: "auc-3",
    category: "Máquinas e Equipamentos",
    subcategory: "Ar Condicionado / Climatização",
    name: "Ar Condicionado Split Carrier Inverter 60.000 BTUs Teto #1",
    description: "Equipamento de grande porte para climatização comercial/industrial, gás R410A, 220V Trifásico.",
    brand: "Carrier",
    model: "Space Inverter 60k",
    serialNumber: "SN-9981245",
    formerAssetTag: "CEF-PATR-4431",
    quantity: 1,
    condition: "usado",
    operationalState: "parcialmente_funcionando",
    location: {
      warehouse: "Depósito Secundário",
      pavilion: "Setor C",
      customText: "Depósito Secundário > Setor C",
    },
    photos: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
    ],
    primaryPhoto: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
    status: "em_manutencao",
    originalCost: 3100.0,
    assignedPercent: 33.33,
    apportionedCost: 3100.0,
    additionalCosts: 450.0, // Higienização + recarga de gás
    realTotalCost: 3550.0,
    estimatedMarketMin: 5500.0,
    estimatedMarketAvg: 6200.0,
    estimatedMarketMax: 6800.0,
    listedPrice: 5900.0,
    isAdvertised: false,
    isSold: false,
    dateAdded: "2026-07-21",
    daysInStock: 6,
    archived: false,
  },
  {
    id: "itm-6",
    code: "LEIL-2026-006",
    lotId: "lot-104",
    auctionId: "auc-1",
    category: "Informática",
    subcategory: "Servidores",
    name: "Servidor Rack Dell PowerEdge R740xd 2U Enterprise",
    description: "Servidor de alta densidade 2U, 2x Intel Xeon Gold 6230, 64GB RAM DDR4 ECC, Controlador PERC H730P 2GB, 2x Fonte Redundante 750W.",
    brand: "Dell Enterprise",
    model: "PowerEdge R740xd",
    serialNumber: "ST-881J2K",
    formerAssetTag: "PATR-TRT-00109",
    quantity: 1,
    condition: "seminovo",
    operationalState: "funcionando",
    location: {
      warehouse: "Galpão Principal",
      pavilion: "Sala Climatizada TI",
      customText: "Galpão Principal > Sala Climatizada TI > Rack 02",
    },
    photos: [
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80",
    ],
    primaryPhoto: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80",
    status: "disponivel",
    originalCost: 9445.0,
    assignedPercent: 100,
    apportionedCost: 9445.0,
    additionalCosts: 0,
    realTotalCost: 9445.0,
    estimatedMarketMin: 14500.0,
    estimatedMarketAvg: 16800.0,
    estimatedMarketMax: 18500.0,
    evaluationSource: "Cotações de Servidores Seminovos SP",
    evaluationDate: "2026-06-25",
    listedPrice: 16200.0,
    isAdvertised: false,
    isSold: false,
    dateAdded: "2026-06-16",
    daysInStock: 41,
    archived: false,
  },
];

export const initialExpenses: AdditionalExpense[] = [
  {
    id: "exp-1",
    itemId: "itm-1",
    category: "Limpeza / Formatação",
    description: "Formatação completa, instalação de licença Windows 11 Pro e substituição da pasta térmica.",
    amount: 150.0,
    date: "2026-06-18",
    supplier: "TechFix Informática LTDA",
  },
  {
    id: "exp-2",
    itemId: "itm-2",
    category: "Manutenção Preventiva",
    description: "Limpeza interna de cooler e higienização do chassis.",
    amount: 80.0,
    date: "2026-06-19",
    supplier: "TechFix Informática LTDA",
  },
  {
    id: "exp-3",
    itemId: "itm-4",
    category: "Estética e Detalhamento Automotivo",
    description: "Polimento técnico, higienização interna de couro, lavagem detalhada de motor e martelinho no para-choque.",
    amount: 2200.0,
    date: "2026-07-06",
    supplier: "AutoBrilho Estética Automotiva",
  },
  {
    id: "exp-4",
    itemId: "itm-4",
    category: "Mecânica / Troca de Óleo",
    description: "Substituição do óleo de motor 5W30, filtro de óleo, filtro de combustível e filtro de ar do motor.",
    amount: 1000.0,
    date: "2026-07-07",
    supplier: "Mecânica ToyoExpert",
  },
  {
    id: "exp-5",
    itemId: "itm-5",
    category: "Manutenção de Ar Condicionado",
    description: "Substituição do capacitor de partida do compressor e carga completa de gás R410A.",
    amount: 450.0,
    date: "2026-07-24",
    supplier: "ClimaFrio Refrigeração",
  },
];

export const initialMaintenanceRecords: MaintenanceRecord[] = [
  {
    id: "maint-1",
    itemId: "itm-5",
    serviceType: "Higienização e Carga de Gás",
    description: "Realizado vácuo no sistema, teste de estanqueidade contra vazamentos e recarga de 3.2kg de gás R410A.",
    date: "2026-07-24",
    responsible: "Eng. Mário Santos",
    supplier: "ClimaFrio Refrigeração",
    cost: 450.0,
    partsUsed: "Gás R410A DuPont (3.2kg), Capacitor 50uF, Veda Rosca Térmico",
    status: "em_manutencao",
    notes: "Aguardando teste final em carga máxima por 2 horas.",
  },
];

export const initialAdvertisements: Advertisement[] = [
  {
    id: "ad-1",
    itemId: "itm-1",
    platform: "Mercado Livre",
    url: "https://produto.mercadolivre.com.br/MLB-398210921-dell-latitude-5420-i7",
    listedPrice: 3500.0,
    publishDate: "2026-06-20",
    adCost: 0,
    status: "vendido",
    notes: "Anúncio Premium com comissão de 12%. Vendido em 18 dias.",
  },
  {
    id: "ad-2",
    itemId: "itm-2",
    platform: "Mercado Livre",
    url: "https://produto.mercadolivre.com.br/MLB-398210922-dell-latitude-5420-i7-seminovo",
    listedPrice: 3450.0,
    publishDate: "2026-06-22",
    adCost: 0,
    status: "publicado",
    notes: "Anúncio ativo com bastante visualizações.",
  },
  {
    id: "ad-3",
    itemId: "itm-2",
    platform: "OLX",
    url: "https://sp.olx.com.br/sao-paulo/dell-latitude-5420-i7-1298129",
    listedPrice: 3350.0,
    publishDate: "2026-06-23",
    adCost: 29.9,
    status: "publicado",
    notes: "Destaque Ouro OLX por 7 dias.",
  },
  {
    id: "ad-4",
    itemId: "itm-4",
    platform: "Webmotors",
    url: "https://www.webmotors.com.br/comprar/toyota/hilux/2021/1289182",
    listedPrice: 174900.0,
    publishDate: "2026-07-08",
    adCost: 189.0,
    status: "publicado",
    notes: "Plano anúncio Ouro com fotos profissionais.",
  },
];

export const initialSales: SaleRecord[] = [
  {
    id: "sale-1",
    itemId: "itm-1",
    buyerName: "Carlos Eduardo Mendes",
    buyerDoc: "289.102.398-11",
    buyerPhone: "(11) 98123-4421",
    buyerEmail: "carlos.mendes@empresa.com.br",
    platform: "Mercado Livre",
    saleDate: "2026-07-08",
    listedPrice: 3500.0,
    negotiatedPrice: 3450.0,
    finalPrice: 3450.0,
    discount: 50.0,
    sellerFreight: 45.0,
    platformCommission: 414.0, // 12%
    taxes: 103.5, // 3% Simples Nacional
    otherExpenses: 0,
    netSaleValue: 2887.5, // 3450 - 45 - 414 - 103.5
    netProfit: 738.21, // 2887.50 - 2149.29
    roiPercentage: 34.35, // (738.21 / 2149.29) * 100
    marginPercentage: 25.57, // (738.21 / 2887.50) * 100
    paymentMethod: "PIX Mercado Pago",
    paymentStatus: "pago",
    notes: "Comprador retirou nota e elogiou o estado do notebook.",
  },
];

export const initialContacts: Contact[] = [
  {
    id: "cnt-1",
    name: "Sodré Santoro Leilões",
    company: "Sodré Santoro Leiloeiros Oficiais",
    docType: "CNPJ",
    docNumber: "51.812.391/0001-09",
    phone: "(11) 2464-6000",
    whatsapp: "(11) 97654-3210",
    email: "atendimento@sodresantoro.com.br",
    address: "Av. do Estado, 4500 - Mooca, São Paulo - SP",
    contactType: "leiloeiro",
    notes: "Plataforma de leilões tradicional em SP.",
  },
  {
    id: "cnt-2",
    name: "TechFix Informática",
    company: "TechFix Manutenção e Serviços LTDA",
    docType: "CNPJ",
    docNumber: "12.345.678/0001-90",
    phone: "(11) 3322-1100",
    whatsapp: "(11) 98888-7777",
    email: "contato@techfix.com.br",
    address: "Rua Santa Ifigênia, 450 - Centro, São Paulo - SP",
    contactType: "prestador",
    notes: "Parceiro para manutenção e formatação rápida de notebooks e desktops.",
  },
  {
    id: "cnt-3",
    name: "TransLeilão Express",
    company: "TransLeilão Logística de Bens EIRELI",
    docType: "CNPJ",
    docNumber: "33.910.221/0001-44",
    phone: "(11) 4004-9911",
    whatsapp: "(11) 99112-2233",
    email: "coletas@transleilao.com.br",
    contactType: "transportadora",
    notes: "Frete especializado para retirada de lotes de leilão com guincho e caminhão baú.",
  },
  {
    id: "cnt-4",
    name: "Carlos Eduardo Mendes",
    docType: "CPF",
    docNumber: "289.102.398-11",
    phone: "(11) 98123-4421",
    email: "carlos.mendes@empresa.com.br",
    contactType: "comprador",
    notes: "Comprador do notebook Dell Latitude 5420.",
  },
];

export const initialDocuments: AppDocument[] = [
  {
    id: "doc-1",
    title: "Edital Oficial Leilão TRT-2 - Ativos de TI",
    docType: "edital",
    entityType: "auction",
    entityId: "auc-1",
    fileName: "Edital_TRT2_2026_TI.pdf",
    fileSize: "2.4 MB",
    uploadDate: "2026-06-10",
  },
  {
    id: "doc-2",
    title: "Nota de Arrematação Lote 15 Sodré Santoro",
    docType: "nota_arrematacao",
    entityType: "lot",
    entityId: "lot-101",
    fileName: "Nota_Arrematacao_Lote15.pdf",
    fileSize: "840 KB",
    uploadDate: "2026-06-16",
  },
  {
    id: "doc-3",
    title: "Comprovante Pagamento PIX Leilão Hilux",
    docType: "comprovante",
    entityType: "lot",
    entityId: "lot-102",
    fileName: "Comprovante_PIX_Hilux_126800.pdf",
    fileSize: "320 KB",
    uploadDate: "2026-07-03",
  },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: "log-1",
    itemId: "itm-1",
    title: "Item Vendido",
    description: "Item vendido por R$ 3.450,00 via Mercado Livre para Carlos Eduardo Mendes. Lucro líquido apurado: R$ 738,21 (ROI: 34,35%).",
    timestamp: "2026-07-08 14:32",
    user: "Administrador",
    type: "sale",
  },
  {
    id: "log-2",
    itemId: "itm-4",
    title: "Novo Anúncio Publicado",
    description: "Toyota Hilux anunciada no Webmotors por R$ 174.900,00.",
    timestamp: "2026-07-08 10:15",
    user: "Administrador",
    type: "ad",
  },
  {
    id: "log-3",
    itemId: "itm-4",
    title: "Despesa Adicionada",
    description: "Transporte e guincho plataforma de R$ 1.500,00 adicionados ao custo real.",
    timestamp: "2026-07-03 16:45",
    user: "Operador",
    type: "expense",
  },
  {
    id: "log-4",
    itemId: "itm-5",
    title: "Alteração para Em Manutenção",
    description: "Ar condicionado Carrier 60k encaminhado para carga de gás e higienização.",
    timestamp: "2026-07-24 09:00",
    user: "Operador",
    type: "maintenance",
  },
  {
    id: "log-5",
    title: "Novo Lote Arrematado",
    description: "Lote 42 do leilão Caixa Econômica cadastrado com valor de lance R$ 7.800,00.",
    timestamp: "2026-07-20 18:20",
    user: "Administrador",
    type: "creation",
  },
];

export const initialAlerts: AlertItem[] = [
  {
    id: "alt-1",
    title: "Prazo limite para retirada de Lote",
    description: "Lote 42 (Ar Condicionado) possui prazo de retirada no galpão de Guarulhos até 30/07/2026.",
    severity: "high",
    dueDate: "2026-07-30",
    relatedType: "lot",
    relatedId: "lot-103",
  },
  {
    id: "alt-2",
    title: "Item sem avaliação de mercado",
    description: "Servidor Rack Dell PowerEdge R740xd necessita de pesquisa de mercado recente.",
    severity: "medium",
    relatedType: "item",
    relatedId: "itm-6",
  },
  {
    id: "alt-3",
    title: "Anúncio sem vendas há mais de 30 dias",
    description: "Notebook Dell Latitude #2 está anunciado há 36 dias sem ofertas convertidas.",
    severity: "info",
    relatedType: "ad",
    relatedId: "ad-2",
  },
];
